---
abstract: 'WebDAO handler for HTTP::Server::Simple'
author:
  - 'Zahatski Aliaksandr zag@cpan.org'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Server-Simple-WebDAO
provides:
  HTTP::Server::Simple::WebDAO:
    file: lib/HTTP/Server/Simple/WebDAO.pm
    version: 0.01
  HTTP::Server::Simple::WebDAO::CVcgi:
    file: lib/HTTP/Server/Simple/WebDAO.pm
    version: 0
requires:
  HTTP::Server::Simple: 0.44
  WebDAO: 2.013
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
