---
abstract: 'WebDAO handler for HTTP::Server::Simple'
author:
  - 'Zahatski Aliaksandr zag@cpan.org'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Server-Simple-WebDAO
provides:
  HTTP::Server::Simple::WebDAO:
    file: lib/HTTP/Server/Simple/WebDAO.pm
    version: 0.03
  HTTP::Server::Simple::WebDAO::CVcgi:
    file: lib/HTTP/Server/Simple/WebDAO.pm
requires:
  HTTP::Server::Simple: 0.44
  WebDAO: 2.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
